### ISSUE TITLE
On Windows 7 machines the compiled version does not detect Tcl

### ISSUE THREAD

**Issue by RedFantom** [RedFantom/GSF-Parser#17]
Only on Windows 7 machines with the installer-version of the parser does the problem occur. Tkinter.py raises a Tkinter.TclError, because the installation of Tcl cannot be found in one of the directories where is being searched. This is a separate issue. DEBUG output:
`Traceback (most recent call last):`
`    File "main.py", line 18, in <module>`
`    File "gui.py", line 29, in __init__`
`    File "lib-tk\mtTkinter.py", line 138, in _Tk__init__`
`    File "lib-tk\Tkinter.py", line 1814, in __init__`
`_tkinter.TclError: Can't find a usable init.tcl in the following directories C:/PROGRA~2/lib/tcl8.5 {C:/Program Files (x86)/lib/tcl8.5} C:/lib/tcl8.5 {C:/Program Files (x86)/library} C:/library C:/tcl8.5.15/library C:/tcl8.5.15/library`

`This probably means that Tcl wasn't installed properly.`

`Failed to execute script main`

**Comment by RedFantom** [comment]
This is a known issue with PyInstaller on Windows 7, more details [here](https://github.com/pyinstaller/pyinstaller/issues/1957).

**Comment by RedFantom** [comment]
More digging into this issue and the way PyInstaller generally works reveals that copying the Tcl folder from the main Python directory into the directory the executable is in might solve the problem. I will try this as soon as possible.

**Comment by smomni** [comment]
Copying a lib (contains tcl8.5 and tk8.5) folder below the app folder fixes this issue for me (frozen app on win7). Appending an arbitrary lib location to sys.path or os.environ['TCL_LIBRARY']/os.environ['TK_LIBRARY'] at runtime, however, does not fix the issue - from which path does tkinter try to find the tcl/tk libraries?

**Comment by RedFantom** [comment]
@smomni Hi there! Sorry for not replying earlier, but finding the time was quite challenging.  Tkinter tries to find the Tcl libraries from a variety of sources, among which indeed the subfolders of the Python installation that it is running in. If copying the folder with the Tcl-libraries fixes the issue, it is strange because PyInstaller actually copies the folders `tcl` and `tk` into the distribution folder, containing the files from `%Pythondir%\tcl\tcl8.5` and `%Pythondir5\tcl\tk8.5` respectively. However, providing a special distribution for the Windows 7 users still out there (I count myself among them, though for me it runs fine because I run the PyInstaller scripts on my local machine) should not be an issue. Thanks for your help!

**Comment by RedFantom** [comment]
Closing the issue was accidental, sorry about that... When running the frozen version of the `stable` branch on a Windows 7 Virtual Machine, the issue still exists. When I copy `tcl8.5` directly into the directory of the GSF Parser, it generates a new error:

    IOError: Tcl data directory "C:\Users\RedFantom\Desktop\GSF Parser\tcl\" not found.
    Failes to execute script pyi_rth_tkinter

When copying the `%Pythondir%\tcl\tcl8.5` folder as both `tcl8.5` and `tcl` (where the latter is automatically done by `PyInstaller`), the main executable raises the same error as before. The same happens for me when copying the `%Pythondir%\tcl` directory into `%GSFParserdir%\lib\tcl` and leaving the `%GSFParserdir%\tcl` directory be.

**Comment by dferrant** [comment]
Here is a workaround I have found working on a freshly installed Windows 7:
```
import sys
from os.path import dirname, join, basename
tcl_lib = join(sys._MEIPASS, "lib")
tcl_new_lib = join(dirname(dirname(tcl_lib)), basename(tcl_lib))
import shutil
shutil.copytree(src=tcl_lib, dst=tcl_new_lib)
```

Put this code before any import of your main script and in your spec file, add this:
```
datas=[('C:\\Python27\\tcl\\tcl8.5', 'lib\\tcl8.5'),
             ('C:\\Python27\\tcl\\tk8.5', 'lib\\tk8.5')]
```

You may also want to delete the created folder at end of execution, but imo not necessary as we work in Temp dir.

**Comment by RedFantom** [comment]
@dferrant 
Thank you for your help on this issue! I have implemented your solution in the branch `pyinstaller`, and I'm testing the solution now. I'll let you know if it works as soon as I can. If I can reproduce that it works, I think you should post it in the issue report of the PyInstaller project, so everyone knows of the solution. Thanks again!

**Comment by RedFantom** [comment]
@dferrant 
Sorry it took me so long to actually test it, but I can confirm that this solution works on my Python installation. Thank you again for the help on this problem!
