### ISSUE TITLE
Ion Railgun not added to list of abilities

### ISSUE THREAD

**Issue by RedFantom** [RedFantom/GSF-Parser#26]
While Ion Railgun does show up in the Events View of the GSF Parser, it never gets added to the list of abilities or the list of components used in the user interface. This is probably an effect of the checks of the GSF Parser to not add Ion Railgun to the list of abilities if only the effects of an upgraded Ion Railgun are applied to the player. The problem is probably caused by code in line 193-200 of `parse.py` and related code in other functions found in the same file. This problem is reproducable by selecting a file with a match with a spawn in which a Mangler with Ion Railgun is flown and checking the abilities and components lists.

**Comment by Zarainia** [comment]
I think the problem is that the AbilityActivate line for ion railgun is always directed to yourself. The code currently only adds it to abilities if the AbilityActivate line _isn't_ directed toward self, so of course it will never be added. Possible fix would be to have it detect damage dealt to another player and add it then.

**Comment by RedFantom** [comment]
I think it's OK if it detects the AoE for the enemies, to be honest. That would actually be my personal preference. It seems to work so far, but I'll make sure before merging your branch into `stable`. So far we've only used the `dev` and `stable` branches, as it's not a really big project, but making more branches would probably be neater. I'll create a merge request and review the changes :) . Using the `in` keyword is preferable in Python when looping over a list, so I changed the style slightly, if that's OK with you. Also, you should start thinking how you want to be listed in the credits (with your Thranta Squadron rank (Ace) or otherwise) ;) .

**Comment by Zarainia** [comment]
Sure, that's fine. I do like the `in` but it makes it hard to check stuff before and after. I guess having an extra variable keeping track of that works as well if that's the preferred style.

**Comment by RedFantom** [comment]
Well, I think it's the preferred way of doing things, but only @naiii can say for sure.

**Comment by RedFantom** [comment]
Consider this issue fixed.
