### ISSUE TITLE
Graph view cut off at edge

### ISSUE THREAD

**Issue by Zarainia** [RedFantom/GSF-Parser#33]
Here is a view of the graph frame, on my computer. The graph is cut off at the right and bottom edges due to the size of the window. 

![graph](https://cloud.githubusercontent.com/assets/14959769/22863723/9e4c475e-f113-11e6-808b-32972dc7fd9f.JPG)

After changing the pyplot.subplot `figsize=(7, 3.7)`, it looks like this, which is much better. 

![graph2](https://cloud.githubusercontent.com/assets/14959769/22863817/c318879a-f114-11e6-9e09-cfde19ea0941.JPG)

If there is a window size parameter somewhere (?), that could be used to adjust the graph size to fit, which would be better than using specific values. Especially, I'm not sure if the GUI is just interacting badly with my computer's setup, which has sizes of objects adjusted to 150% of their normal size (it's a small, high-resolution laptop screen). Older style GUIs do tend to have problems with blurriness and/or things being cut off while using the magnification, so that may be the explanation if no one else is experiencing the problem. 

![sizeadjust](https://cloud.githubusercontent.com/assets/14959769/22863797/914aa982-f114-11e6-9f11-9c2a5dd2a041.JPG)

**Comment by RedFantom** [comment]
Wow, that's interesting indeed. The plot features of matplotlib do have a `dpi` keyword-argument, so it probably has something to do with that. The graphs should actually look a lot more like this:
![graph](https://cloud.githubusercontent.com/assets/15170036/22864153/388e603a-f14c-11e6-8b86-824321e0dee1.png)
Maybe using the `dpi` keyword, there's the possibility of making it look the same on all computers in one go. If not, there are two options: determining the right settings for every dpi-setting within Windows, or letting the users set the graph size themselves (which is the worst idea of the two).

**Comment by Zarainia** [comment]
This might not be the issue, actually. I turned off the scaling thing and the window still looks the same, just the entire thing is smaller.

**Comment by RedFantom** [comment]
All right, so it's platform dependent. That's pretty annoying, actually. I'll try to get the right values using my VMs.

**Comment by RedFantom** [comment]
On my Windows 10 VM the graph view is not cut off, strangely enough. This is using `v2.5.3` of the GSF Parser, which does not even include the `dpi` keyword argument in the creation of the `Figure` from the `matplotlib` module. You did restart your computer after changing DPI scaling, right?

**Comment by Zarainia** [comment]
Yep, I restarted. I think the scaling just stretches the entire window. Though I don't know why the graph would be the wrong side inside the window...

**Comment by Zarainia** [comment]
I tried disabling the scaling just for this program, and it is no longer blurry, which is nice. However, it is now cut off at the edges for all tabs. Is there a parameter somewhere setting the window size? Maybe scaling that somehow would help with both problems. Or allowing resizing it? 

![image](https://cloud.githubusercontent.com/assets/14959769/23280094/df6c4d08-f9e5-11e6-932e-0270209eff0e.png)

**Comment by RedFantom** [comment]
Well, the graph is based on a `Canvas`. The `Canvas` is a widget that allows direct drawing, completely bypassing anything about size that Windows might want. If I allow resizing of the window, the widgets would have to scale along with it. Now, for the widgets that use the `sticky=tk.N+tk.S+tk.W(+tk.E)` attribute, that's not much of a problem. However, `Listbox`es for example require a `width` or another parameter so they don't default to the wrong size. Making the window resizable would have to use a callback to resize all these widgets, and preferably the font size through configure style `"."` as well. However, I find the idea of this more daunting than anything, really. Just not having resizability makes things so much easier... It is possible to change just the window size in the `gui.py` file in the `wm_geometry` call, but most of the frames have specified sizes as well (most of them stretch to fit though).

**Comment by Zarainia** [comment]
Changing the geometry thing in the gui's init allowed me to make everything visible. Maybe a setting could be made linked to that. Scaling it automatically would be better, of course, but it's kind of mysterious what's causing this so there's no way to know when to scale of but how much.

**Comment by RedFantom** [comment]
Unless we could use `Tkinter`'s functions to determine required widget size... Though I do not remember them from the top of my head.

**Comment by Zarainia** [comment]
Do that widgets have a particular size?

**Comment by RedFantom** [comment]
Some of them do, such as the `Listbox` has a default width of 10, I think. That's not how many characters fit in the `Listbox`, as that also depends on the font used. It is quite complicated really. You're not the first one to say that the window should be resizable though, so I think it would at least be a good idea to consider a `callback` to use the `config` function of all widgets to reconfigure their size upon resizing the window. A minimum size would be required though... And it would also be best to have the fonts of the `Label`s to scale with the size of the window.

On-topic: I still think it must have something to do with the DPI settings within Windows. I'll try using the setting on a Windows 7 VM, because of Windows 10 not playing nice with the VM at all.

**Comment by RedFantom** [comment]
![image](https://cloud.githubusercontent.com/assets/15170036/23570759/15afb8ce-0066-11e7-86b7-04c74a8215e3.png)
Nightmaregale has reported this issue as well under Windows 10.

**Comment by RedFantom** [comment]
This problem is *not* reproducable for me when using a Windows 10 VM, PyCharm and running the source code of the `graphs_edge` branch, but I can reproduce it with code from the `development` branch.

**Comment by RedFantom** [comment]
That fixes the problem. @Zarainia Feel free to reopen the issue if you are still experiencing the issue when using the latest from the `development`-branch.
