### ISSUE TITLE
TclError when selecting single spawn of match

### ISSUE THREAD

**Issue by RedFantom** [RedFantom/GSF-Parser#48]
This error occurs with the following file: [combat_2017-02-19_16_01_53_560319.txt](https://github.com/RedFantom/GSF-Parser/files/786003/combat_2017-02-19_16_01_53_560319.txt) in the match of 17:07:53 in the spawn of 17:07:53 for me. On other files I have not yet seen this error. Also noteworthy: if I recall correctly, there should be multiple spawns in that match, as I have not played a single match today in which I didn't die at least once.

    Exception in Tkinter callback
    Traceback (most recent call last):
      File "C:\Python_2.7\lib\lib-tk\Tkinter.py", line 1536, in __call__
        return self.func(*args)
      File "C:\Users\RedFantom\Source Code\GSF-Parser\fileframe.py", line 461, in spawn_update
        self.spawn_box.itemconfig(self.old_spawn, background="white")
      File "C:\Python_2.7\lib\lib-tk\Tkinter.py", line 2681, in itemconfigure
        return self._configure(('itemconfigure', index), cnf, kw)
      File "C:\Python_2.7\lib\lib-tk\Tkinter.py", line 1317, in _configure
        self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
      File "C:\Python_2.7\lib\lib-tk\mtTkinter.py", line 108, in __call__
    TclError: item number "4" out of range

**Comment by Zarainia** [comment]
I've gotten a similar issue a few times (also with selecting a match), but when I restart the program, it works again.

**Comment by RedFantom** [comment]
OK, that means there's probably a variable that's not getting flushed correctly. I'll investigate.

**Comment by RedFantom** [comment]
While its not a very efficient solution, it is the easiest and best solution I could think of. I will create a pull request to get the solution to the `development` branch.

**Comment by RedFantom** [comment]
Merged into `development` branch. That should do it.
