### ISSUE TITLE
Setting for Republic ships 

### ISSUE THREAD

**Issue by RedFantom** [RedFantom/GSF-Parser#74]
In commit  c41bec8, @Zarainia added the images required for the Republic ships to be displayed in the user interface. To fully implement this feature, the following checklist should be completed:
- Add setting to the settings frame with radiobuttons
- Add setting to the settings class for saving in the settings file
- Add setting to the settings importer
- Enable the translation of file names and ship names using a dictionary

It would be even better to integrate with the character manager that is planned in the build frame to allow the user to select what characters are Republic and what characters are Imperial.

**Comment by Zarainia** [comment]
Made a new branch for this because I forgot to update before making the changes.

**Comment by RedFantom** [comment]
Merged! Thanks @Zarainia !
