### ISSUE TITLE
Character GUI profile only saves when Auto-Detect is used

### ISSUE THREAD

**Issue by Zarainia** [RedFantom/GSF-Parser#90]
When I manually select a GUI profile from the dropdown and press save, the changes are not saved. Closing and opening the Parser will revert the GUI profile to what it was before, and the file name used for realtime parsing is the same as it was previously. However, it is saved correctly when I press "auto-detect" instead and then save.

**Comment by RedFantom** [comment]
You did press the `Save`-button right? Because using auto-detect does an auto-save, but selecting it from the dropdown doesn't (I can't do a `command=` keyword argument for an `OptionMenu`.

In any case, I'll look into it.

**Comment by Zarainia** [comment]
I did press save, and it showed in the console as well.

**Comment by RedFantom** [comment]
@Zarainia Thank you for spotting these! If you find any more issues, please let me know :)
